"""add workflow acoes

Revision ID: a086da33c6f7
Revises: 
Create Date: 2025-12-01 00:22:22.446903

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a086da33c6f7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chamado', schema=None) as batch_op:
        batch_op.alter_column('criado_por',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chamado', schema=None) as batch_op:
        batch_op.alter_column('criado_por',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
